import { manufactures, collectionsFor } from "@/content/watches";
import { email, phone, required } from "./validators";
import { grp, str, type Answers, type FlowConfig } from "./types";

const PRIVATE_BANDS = ["£100k–£250k", "£250k–£500k", "£500k+", "£1m+"];

export const horologyAcquire: FlowConfig = {
  id: "horology-acquire",
  house: "horology",
  kind: "acquisition",
  title: ["The Velmont", "Watch Mandate"],
  greetingSub: "Let’s find the piece.",
  submitLabel: "Submit Watch Mandate",
  privateSubmitLabel: "Submit Private Client Mandate",
  confirmationHeadline: ["Your mandate", "has been received."],
  confirmationBody:
    "A member of the Velmont Private Watch Office will review your mandate and be in touch at the time you suggested.",
  isPrivateMandate: (a) =>
    PRIVATE_BANDS.includes(str(a, "budget")) ||
    str(a, "budgetPosition") === "The right piece matters more than the budget.",
  steps: [
    {
      kind: "choice",
      id: "intent",
      label: "The Search",
      question: "What are we searching for?",
      columns: 2,
      options: [
        "A specific reference",
        "A specific model",
        "A specific manufacture",
        "A rare or discontinued piece",
        "An investment or collector piece",
        "A first serious watch",
        "A gift",
        "Build a collection",
        "Advise me",
      ],
    },
    {
      kind: "select",
      id: "manufacture",
      label: "Manufacture",
      question: "Which manufacture?",
      options: [...manufactures],
      placeholder: "Begin typing a manufacture…",
      when: (a) => str(a, "intent") !== "Advise me",
    },
    {
      kind: "select",
      id: "collection",
      label: "Model / Collection",
      question: "Which collection?",
      options: (a) => collectionsFor(str(a, "manufacture")),
      placeholder: "Begin typing…",
      when: (a) => !!str(a, "manufacture") && str(a, "manufacture") !== "Other",
    },
    {
      kind: "choice",
      id: "reference",
      label: "Reference",
      question: "Do you know the reference?",
      options: ["I know the exact reference", "I don’t know the reference"],
      detailOn: ["I know the exact reference"],
      detailLabel: "The reference number",
    },
    {
      kind: "choice",
      id: "year",
      label: "Year",
      question: "From which era?",
      options: ["A specific year", "A range of years", "Modern", "Vintage", "No preference"],
      detailOn: ["A specific year", "A range of years"],
      detailLabel: "The year, or range",
    },
    {
      kind: "choice",
      id: "condition",
      label: "Condition",
      question: "What condition would you accept?",
      options: [
        "Unworn",
        "Excellent",
        "Pre-owned considered",
        "Vintage appropriate",
        "No preference",
      ],
    },
    {
      kind: "choice",
      id: "set",
      label: "The Set",
      question: "Box and papers?",
      columns: 2,
      options: [
        "Full set required",
        "Box preferred",
        "Papers required",
        "Extract or archive acceptable",
        "Watch only considered",
        "No preference",
      ],
    },
    {
      kind: "group",
      id: "dial",
      label: "The Dial",
      question: "Tell us about the dial.",
      optional: true,
      fields: [
        { id: "colour", label: "Colour", optional: true, placeholder: "Salmon, black lacquer, blue soleil…" },
        { id: "configuration", label: "Configuration", optional: true, placeholder: "No date, panda, gilt…" },
        { id: "rare", label: "Rare dial requirements", optional: true, placeholder: "If any" },
      ],
    },
    {
      kind: "choice",
      id: "caseMaterial",
      label: "Case",
      question: "Which case material?",
      columns: 2,
      options: [
        "Steel",
        "Yellow gold",
        "Rose gold",
        "White gold",
        "Platinum",
        "Titanium",
        "Ceramic",
        "Other",
      ],
      detailOn: ["Other"],
      detailLabel: "Tell us the material",
    },
    {
      kind: "choice",
      id: "size",
      label: "Size",
      question: "And the size?",
      options: ["An exact size", "A range", "No preference"],
      detailOn: ["An exact size", "A range"],
      detailLabel: "In millimetres",
    },
    {
      kind: "choice",
      id: "bracelet",
      label: "Bracelet / Strap",
      question: "How should it wear?",
      options: [
        "Original bracelet required",
        "Leather",
        "Rubber",
        "Either",
        "Other",
      ],
      detailOn: ["Other"],
      detailLabel: "Tell us more",
    },
    {
      kind: "choice",
      id: "provenance",
      label: "Provenance",
      question: "Does history matter here?",
      columns: 2,
      options: [
        "Original purchase documentation",
        "Service history",
        "Single owner preferred",
        "Auction provenance",
        "Important provenance",
        "No specific requirement",
      ],
    },
    {
      kind: "choice",
      id: "budget",
      label: "Budget",
      question: "Where shall we work?",
      columns: 2,
      options: [
        "£10k–£25k",
        "£25k–£50k",
        "£50k–£100k",
        "£100k–£250k",
        "£250k–£500k",
        "£500k+",
        "£1m+",
        "A custom figure",
      ],
      detailOn: ["A custom figure"],
      detailLabel: "The figure you have in mind",
    },
    {
      kind: "choice",
      id: "budgetPosition",
      label: "Budget",
      question: "And how firmly?",
      options: [
        "Work within the budget",
        "The right piece matters more than the budget.",
      ],
    },
    {
      kind: "choice",
      id: "timeframe",
      label: "Timeframe",
      question: "When should it arrive?",
      columns: 2,
      options: [
        "Immediately",
        "Within 30 days",
        "Within 3 months",
        "Within 6 months",
        "No deadline",
        "Waiting for the right piece",
      ],
    },
    {
      kind: "choice",
      id: "purpose",
      label: "Purpose",
      question: "What is this piece for?",
      columns: 2,
      options: [
        "Personal collection",
        "Daily wear",
        "A milestone",
        "A gift",
        "Long-term collection",
        "Other",
      ],
      detailOn: ["Other"],
      detailLabel: "Tell us more",
    },
    {
      kind: "choice",
      id: "disposal",
      label: "Disposal",
      question: "Is there a timepiece you would consider selling or trading?",
      options: ["Yes", "No"],
    },
    {
      kind: "group",
      id: "disposalDetails",
      label: "Disposal",
      question: "Tell us about it.",
      when: (a) => str(a, "disposal") === "Yes",
      fields: [
        { id: "manufacture", label: "Manufacture", validate: required },
        { id: "model", label: "Model", validate: required },
        { id: "reference", label: "Reference", optional: true },
        { id: "year", label: "Year", optional: true },
        { id: "condition", label: "Condition", optional: true },
        { id: "set", label: "Box and papers", optional: true, placeholder: "Full set, box only…" },
        { id: "service", label: "Service history", optional: true },
        { id: "expectation", label: "Expected value", optional: true },
      ],
    },
    {
      kind: "upload",
      id: "disposalPhotos",
      label: "Disposal",
      question: "A few photographs help.",
      optional: true,
      when: (a) => str(a, "disposal") === "Yes",
    },
    {
      kind: "choice",
      id: "collectionSize",
      label: "Your Collection",
      question: "How many watches are currently in your collection?",
      hint: "Entirely optional — every collection starts somewhere.",
      optional: true,
      options: ["1", "2–5", "6–10", "11–25", "25+", "I’d rather not say"],
    },
    {
      kind: "group",
      id: "collectionProfile",
      label: "Your Collection",
      question: "Where is your collection heading?",
      hint: "Optional — it simply helps us look further ahead for you.",
      optional: true,
      fields: [
        { id: "manufactures", label: "Manufactures you collect", optional: true },
        { id: "direction", label: "The direction you’d like to take", optional: true },
      ],
    },
    {
      kind: "group",
      id: "client",
      label: "Your Details",
      question: "How shall we address you?",
      fields: [
        { id: "firstName", label: "First name", validate: required, autoComplete: "given-name" },
        { id: "surname", label: "Surname", validate: required, autoComplete: "family-name" },
        { id: "email", label: "Email", type: "email", validate: email, autoComplete: "email" },
        { id: "mobile", label: "Mobile", type: "tel", validate: phone, autoComplete: "tel" },
      ],
    },
    {
      kind: "choice",
      id: "contactPreference",
      label: "Contact",
      question: "How shall we reach you?",
      options: ["Telephone", "WhatsApp", "Email"],
    },
    {
      kind: "choice",
      id: "bestTime",
      label: "Contact",
      question: "When suits you best?",
      options: ["Morning", "Afternoon", "Evening", "A specific time"],
      detailOn: ["A specific time"],
      detailLabel: "The time that suits",
    },
    {
      kind: "textarea",
      id: "notes",
      label: "In Closing",
      question: "Is there anything else that would help us find the right piece?",
      optional: true,
      placeholder: "Pieces you’ve admired, dials you’ve hunted, details that matter.",
    },
  ],
  review: (a: Answers) => {
    const manufacture = str(a, "manufacture");
    const collection = str(a, "collection");
    const heroLines =
      manufacture && manufacture !== "Other"
        ? [manufacture, collection && collection !== "Other" ? collection : ""]
        : [str(a, "intent") || "Advisory mandate"];
    const details = [
      str(a, "referenceDetail"),
      str(a, "yearDetail") || (str(a, "year") === "No preference" ? "" : str(a, "year")),
      grp(a, "dial").colour && `${grp(a, "dial").colour} dial`,
      str(a, "caseMaterialDetail") || (str(a, "caseMaterial") !== "Other" ? str(a, "caseMaterial") : ""),
      str(a, "set") === "No preference" ? "" : str(a, "set"),
    ].filter(Boolean) as string[];
    const facts = [
      { label: "Budget", value: str(a, "budgetDetail") || str(a, "budget") },
      { label: "Timeframe", value: str(a, "timeframe") },
      { label: "Condition", value: str(a, "condition") },
      str(a, "disposal") === "Yes"
        ? {
            label: "Disposal",
            value: [grp(a, "disposalDetails").manufacture, grp(a, "disposalDetails").model]
              .filter(Boolean)
              .join(" "),
          }
        : null,
    ].filter(Boolean) as { label: string; value: string }[];
    return { heroLines: heroLines.filter(Boolean), details, facts };
  },
};
